@startuml UseCaseModel

skinparam actorStyle awesome
skinparam packageStyle rectangle

actor FietstochtenAdmin as FTA
actor GolfdagenAdmin as GA
actor AmbassadeursAdmin as AA
actor FinancienAdmin as FA
actor Secretaris as S
actor Timer as T 

package BerghAdmin {
    usecase (Beheer Fietstochten) as UC1
    usecase (Beheer Golfdagen) as UC2
    usecase (Beheer Ambassadeurs) as UC3
    usecase (Beheer Financien) as UC4
}

package Algemeen {
    usecase (Beheer Personen) as UC5
    usecase (Verstuur emails) as UC6
    usecase (Maak en\nstuur factuur) as UC7
    usecase (Lees Kentaa\ninformatie) as UC8
}

FTA --> UC1
GA --> UC2
AA --> UC3

FA --> UC4

S -up-> UC5
S -up-> UC6
S -up-> UC7

T -up-> UC8

UC1 --> UC5
UC2 --> UC5
UC3 --> UC5
UC1 --> UC6
UC2 --> UC6
UC3 --> UC6
UC2 --> UC7
UC3 --> UC7
UC4 --> UC7
BerghAdmin .down.> Algemeen

@enduml
