// <auto-generated />
using System;
using bihz.kantoorportaal.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace bihz.kantoorportaal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bihz.kantoorportaal.Data.Persoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Achternaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GeboorteDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Geslacht")
                        .HasColumnType("int");

                    b.Property<string>("Land")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobiel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voorletters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Achternaam = "Happie",
                            Adres = "Straat 1",
                            EmailAdres = "ahappie@mail.com",
                            GeboorteDatum = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Geslacht = 1,
                            Land = "Nederland",
                            Mobiel = "06-12345678",
                            Plaats = "Amsterdam",
                            Postcode = "1234 AB",
                            Telefoon = "onbekend",
                            Voorletters = "A. B.",
                            Voornaam = "Appie"
                        },
                        new
                        {
                            Id = 2,
                            Achternaam = "Bengel",
                            Adres = "Straat 2",
                            EmailAdres = "bbengel@mail.com",
                            GeboorteDatum = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Geslacht = 1,
                            Land = "Nederland",
                            Mobiel = "06-12345678",
                            Plaats = "Rotterdam",
                            Postcode = "4321 AB",
                            Telefoon = "onbekend",
                            Voorletters = "B.",
                            Voornaam = "Bert"
                        });
                });

            modelBuilder.Entity("bihz.kantoorportaal.Data.PersoonRol", b =>
                {
                    b.Property<int>("PersoonId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("PersoonId", "RolId");

                    b.ToTable("PersoonRol");
                });

            modelBuilder.Entity("bihz.kantoorportaal.Data.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rollen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschrijving = "Renner"
                        },
                        new
                        {
                            Id = 2,
                            Beschrijving = "Begeleider"
                        },
                        new
                        {
                            Id = 3,
                            Beschrijving = "Reserve"
                        },
                        new
                        {
                            Id = 4,
                            Beschrijving = "Commissielid"
                        },
                        new
                        {
                            Id = 5,
                            Beschrijving = "Vriend van"
                        },
                        new
                        {
                            Id = 6,
                            Beschrijving = "Mailing abonnee"
                        },
                        new
                        {
                            Id = 7,
                            Beschrijving = "Golfer"
                        },
                        new
                        {
                            Id = 8,
                            Beschrijving = "Ambassadeur"
                        });
                });

            modelBuilder.Entity("PersoonRol", b =>
                {
                    b.Property<int>("PersonenId")
                        .HasColumnType("int");

                    b.Property<int>("RollenId")
                        .HasColumnType("int");

                    b.HasKey("PersonenId", "RollenId");

                    b.HasIndex("RollenId");

                    b.ToTable("PersoonInRol");
                });

            modelBuilder.Entity("PersoonRol", b =>
                {
                    b.HasOne("bihz.kantoorportaal.Data.Persoon", null)
                        .WithMany()
                        .HasForeignKey("PersonenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bihz.kantoorportaal.Data.Rol", null)
                        .WithMany()
                        .HasForeignKey("RollenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
