# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: targetEnvironment # where to deploy
  type: string # data type of the parameter; required
  default: test
  values:
  - test
  - prod

trigger:
- master

stages:
- stage: BuildAndTest
  displayName: Build and Test
  pool:
    vmImage: ubuntu-latest
  
  jobs:
  - job: Build_Test_Publish
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Test'
      inputs:
        command: 'test'
        projects: '**/*.Tests.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Publish website'
      inputs:
        command: 'publish'
        arguments: '-o $(Build.ArtifactStagingDirectory)'
        projects: '**/*.csproj'
        publishWebProjects: false
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy2BerghTest
  displayName: Deploy new version to Azure test 

  jobs:
  - job: deploy_to_bergh_test
    displayName: Deploy to Bergh Test
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
  
    - template: release-bergh-components.yml
      parameters: 
        targetEnvironment: test


- stage: Deploy2BerghProd
  displayName: Deploy new version to Azure prod

  jobs:
  - job: deploy_to_bergh_prod
    displayName: Deploy to Bergh Test
    steps:

    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'  

    - template: release-bergh-components.yml
      parameters: 
        targetEnvironment: prod
