# Pipeline to provision infra components in azure for testing
trigger:
- none

pool:
  vmImage: windows-latest

parameters:
- name: TargetEnvironment # where to deploy
  type: string # data type of the parameter; required
  default: test
  values:
    - test
    - prod

steps:
- script: echo New infrastructure for ${{ parameters.TargetEnvironment }} will be provisioned
  displayName: 'Provision ${{ parameters.TargetEnvironment }} infra on Azure'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'BerghAzureResourceMgr'
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: 'Provision/provision-infra.azcli.ps1'
    arguments: > 
        -env '${{ parameters.TargetEnvironment }}'
