version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty@123
      MYSQL_DATABASE: BIHZ2021
      MYSQL_USER: BerghAdmin
      MYSQL_PASSWORD: qwerty@123
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - berghnetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - berghnetwork

volumes:
  mysqldata:

networks:
  berghnetwork: